initial: step1
final: [step2]

states:
  - name: step1
    class_: .states.step1.Step1 #相對 module path
    to: subflow_a

  - name: subflow_a
    subflow: playbook:subflows/subflow_a/playbook.yaml
    # class_ 可省略，Playbook.get_state_constructor() 會自動用 Orchestrator

  - name: step2
    class_: .states.step2.Step2 # 相對於當前 playbook.yaml 的 module path
