[project]
name = "am-core"
version = "0.2.0"
description = "ActionManifold Core Engine (Design-time + Runtime)"
authors = [
    { name = "Young-Chung Hsue" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "click",
    "importlib-metadata",
    "networkx"
]

[project.optional-dependencies]
dev = ["pytest", 
    "pytest-asyncio",
    "rich",
    "python-dotenv"
]

# 這裡是重點：建立 am 指令
[project.scripts]
am-design = "am_core.design_cli.cli:main"
am-run = "am_core.runtime_cli.cli:cli"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]