initial: a1
final: [a2]

states:
  - name: a1
    class_: .states.a1.A1 #相對 module path
    to: a2

  - name: subflow_b
    subflow: playbook:subflow_b/playbook.yaml
    # class_ 可省略，Playbook.get_state_constructor() 會自動用 Orchestrator

  - name: a2
    class_: .states.a2.A2 # 相對於當前 playbook.yaml 的 module path